"""add_manager_user.

Revision ID: 2c93908d97c6
Revises: 7e78d13ef979
Create Date: 2024-03-06 13:20:37.049633

"""
from __future__ import annotations

from typing import Sequence

from alembic import op
from sqlalchemy.orm import sessionmaker

from domain.models import User
from infrastructure import ID_MANAGER

# revision identifiers, used by Alembic.
revision: str = "2c93908d97c6"
down_revision: str | None = "7e78d13ef979"
branch_labels: str | Sequence[str] | None = None
depends_on:  str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = sessionmaker(bind=bind)()
    manager = {"name": "Менеджер", "phone": "+7 (800) 444-15-39", "email": "support23@flagman-it.ru",
               "id": ID_MANAGER,
               "password": "$2b$12$Dq3sstEXOtS7QZwkz/kbleR0W1aEsS0xeGcTn2SN0pJEEB.3w.OfS"}

    user = User(**manager)
    session.add(user)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
