"""initall.

Revision ID: 7e78d13ef979
Revises:
Create Date: 2024-03-06 13:20:31.035663

"""
from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e78d13ef979"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("chat",
                    sa.Column("name", sa.String(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint("id"),
                    )
    op.create_table("file",
                    sa.Column("name", sa.String(), nullable=False),
                    sa.Column("path", sa.String(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint("id"),
                    )
    op.create_table("permission",
                    sa.Column("name", sa.String(length=256), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint("id"),
                    sa.UniqueConstraint("name"),
                    )
    op.create_table("role",
                    sa.Column("name", sa.String(length=256), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint("id"),
                    sa.UniqueConstraint("name"),
                    )
    op.create_table("user",
                    sa.Column("name", sa.String(), nullable=True),
                    sa.Column("email", sa.String(length=256), nullable=False),
                    sa.Column("phone", sa.String(length=256), nullable=False),
                    sa.Column("password", sa.String(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint("id"),
                    sa.UniqueConstraint("email"),
                    sa.UniqueConstraint("phone"),
                    )
    op.create_table("associative_role_permission",
                    sa.Column("role_id", sa.Uuid(), nullable=False),
                    sa.Column("permission_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(["permission_id"], ["permission.id"], ondelete="CASCADE"),
                    sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint("role_id", "permission_id", "id"),
                    )
    op.create_index(op.f("ix_associative_role_permission_permission_id"), "associative_role_permission",
                    ["permission_id"], unique=False)
    op.create_index(op.f("ix_associative_role_permission_role_id"), "associative_role_permission", ["role_id"],
                    unique=False)
    op.create_table("associative_user_chat",
                    sa.Column("user_id", sa.Uuid(), nullable=False),
                    sa.Column("chat_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
                    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint("user_id", "chat_id", "id"),
                    )
    op.create_index(op.f("ix_associative_user_chat_chat_id"), "associative_user_chat", ["chat_id"], unique=False)
    op.create_index(op.f("ix_associative_user_chat_user_id"), "associative_user_chat", ["user_id"], unique=False)
    op.create_table("associative_user_role",
                    sa.Column("user_id", sa.Uuid(), nullable=False),
                    sa.Column("role_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
                    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint("user_id", "role_id", "id"),
                    )
    op.create_index(op.f("ix_associative_user_role_role_id"), "associative_user_role", ["role_id"], unique=False)
    op.create_index(op.f("ix_associative_user_role_user_id"), "associative_user_role", ["user_id"], unique=False)
    op.create_table("message",
                    sa.Column("data", sa.JSON(), nullable=False),
                    sa.Column("type", sa.String(), nullable=False),
                    sa.Column("chat_id", sa.Uuid(), nullable=False),
                    sa.Column("user_id", sa.Uuid(), nullable=False),
                    sa.Column("id", sa.Uuid(), nullable=False),
                    sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"),
                              nullable=False),
                    sa.Column("is_removing", sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(["chat_id"], ["chat.id"], ondelete="CASCADE"),
                    sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
                    sa.PrimaryKeyConstraint("id"),
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    op.drop_index(op.f("ix_associative_user_role_user_id"), table_name="associative_user_role")
    op.drop_index(op.f("ix_associative_user_role_role_id"), table_name="associative_user_role")
    op.drop_table("associative_user_role")
    op.drop_index(op.f("ix_associative_user_chat_user_id"), table_name="associative_user_chat")
    op.drop_index(op.f("ix_associative_user_chat_chat_id"), table_name="associative_user_chat")
    op.drop_table("associative_user_chat")
    op.drop_index(op.f("ix_associative_role_permission_role_id"), table_name="associative_role_permission")
    op.drop_index(op.f("ix_associative_role_permission_permission_id"), table_name="associative_role_permission")
    op.drop_table("associative_role_permission")
    op.drop_table("user")
    op.drop_table("role")
    op.drop_table("permission")
    op.drop_table("file")
    op.drop_table("chat")
    # ### end Alembic commands ###
